name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GPT3_TOKEN: ${{ secrets.GPT3_TOKEN }}
